### ISSUE TITLE
Timeout Request

### ISSUE THREAD

**Issue by riverojohnatan** [jarrodek/ChromeRestClient#665]
When a POST request is made, that request is in an infinite loop and ends up throwing a timeout. The same request in another rest client runs correctly.
I hope you can fix it
## Versions

App: 7.16.33.191-stable
Chrome: 50.0.2661.94
Platform: Linux (-)

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
I hope I can fix it but I need more data :) Do you know what causing the loop? Can you see anything in logs that can suggest a problem?

**Comment by riverojohnatan** [comment]
The server ends the process without problems, but the app does not recive the answer until I turn down the server. 
On server-side, i see that this is getting several request at the same time from the app

**Comment by jarrodek** [comment]
In left panel there is a log viewer (under "more" icon"). Can you paste the part when you are making a request and the response is reported? It will help a lot.

**Comment by riverojohnatan** [comment]
the app is not logged requests that failed. But I upload the log JSON

[
  {
    "type": "log",
    "stack": [
      "    at arc-response-status-view.Polymer._onStatusInfoReady (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:58188:13)",
      "    at arc-status-object-model.handler (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:3323:17)",
      "    at arc-status-object-model.Polymer.Base._addFeature.fire (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4079:6)",
      "    at arc.app.db.idb.open.then.then (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:52809:14)",
      "    at N (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/bower_components/dexie-js/dist/dexie.min.js:1:6469)",
      "    at B.V (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/bower_components/dexie-js/dist/dexie.min.js:1:7633)",
      "    at M (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/bower_components/dexie-js/dist/dexie.min.js:1:7343)",
      "    at chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/bower_components/dexie-js/dist/dexie.min.js:1:7289",
      "    at L.i (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/bower_components/dexie-js/dist/dexie.min.js:1:7873)"
    ],
    "time": 1461353104601,
    "logs": "[{\"key\":200,\"label\":\"OK\",\"desc\":\"Standard response for successful HTTP requests. The actual response will depend on the request method used. In a GET request, the response will contain an entity corresponding to the requested resource. In a POST request the response will contain an entity describing or containing the result of the action.\"}]"
  },
  {
    "type": "log",
    "stack": [
      "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
      "    at SocketFetch.disconnect (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24440:10)",
      "    at SocketFetch._cleanUpRedirect (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25145:17)",
      "    at SocketFetch._cleanUp (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25133:10)",
      "    at _createResponse.then (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25118:14)"
    ],
    "time": 1461353104481,
    "logs": "[\"Disconnect\"]"
  },
  {
    "type": "log",
    "stack": [
      "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
      "    at SocketFetch.readSocketError (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24840:10)",
      "    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)",
      "    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)",
      "    at EventImpl.dispatch_ (extensions::event_bindings:371:35)",
      "    at dispatchArgs (extensions::event_bindings:243:26)",
      "    at dispatchEvent (extensions::event_bindings:252:7)"
    ],
    "time": 1461353104480,
    "logs": "[\"Exit code:\",100]"
  },
  {
    "type": "log",
    "stack": [
      "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
      "    at SocketFetch._processBody (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25024:14)",
      "    at SocketFetch._processSocketMessage (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24885:12)",
      "    at SocketFetch.readSocketData (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24822:14)",
      "    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)",
      "    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)",
      "    at EventImpl.dispatch_ (extensions::event_bindings:371:35)",
      "    at dispatchArgs (extensions::event_bindings:243:26)",
      "    at dispatchEvent (extensions::event_bindings:252:7)"
    ],
    "time": 1461353104478,
    "logs": "[\"Creating new body\"]"
  },
  {
    "type": "log",
    "stack": [
      "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
      "    at SocketFetch._processBody (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24989:10)",
      "    at SocketFetch._processSocketMessage (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24885:12)",
      "    at SocketFetch.readSocketData (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24822:14)",
      "    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)",
      "    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)",
      "    at EventImpl.dispatch_ (extensions::event_bindings:371:35)",
      "    at dispatchArgs (extensions::event_bindings:243:26)",
      "    at dispatchEvent (extensions::event_bindings:252:7)"
    ],
    "time": 1461353104476,
    "logs": "[\"Processing body\"]"
  },
  {
    "type": "log",
    "stack": [
      "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
      "    at SocketFetch._parseHeaders (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25201:10)",
      "    at SocketFetch._processHeaders (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24938:10)",
      "    at SocketFetch._processSocketMessage (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24879:19)",
      "    at SocketFetch.readSocketData (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24822:14)",
      "    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)",
      "    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)",
      "    at EventImpl.dispatch_ (extensions::event_bindings:371:35)",
      "    at dispatchArgs (extensions::event_bindings:243:26)"
    ],
    "time": 1461353104475,
    "logs": "[\"Received headers list\",\"Content-Type: application/json;charset=UTF-8\\r\\nServer: Jetty(9.0.2.v20130417)\\r\\nConnection: close\\r\\nSet-Cookie: f5avrbbbbbbbbbbbbbbbb=ADBKGHNJLLKCBAJKFDGFGPOEADFPHOGKAAINLBBFINNDPKMHPDADFAJIODJAJGGONKAHPMDADDJEDDPDDHGHDBHMKMIBKPLJDHBPICEEPKIPEFHGCMNHMGAKJKCDBJFO; HttpOnly\",{\"Content-Type\":\"application/json;charset=UTF-8\",\"Server\":\"Jetty(9.0.2.v20130417)\",\"Connection\":\"close\",\"Set-Cookie\":\"f5avrbbbbbbbbbbbbbbbb=ADBKGHNJLLKCBAJKFDGFGPOEADFPHOGKAAINLBBFINNDPKMHPDADFAJIODJAJGGONKAHPMDADDJEDDPDDHGHDBHMKMIBKPLJDHBPICEEPKIPEFHGCMNHMGAKJKCDBJFO; HttpOnly\"}]"
  }
]

**Comment by doubotis** [comment]
Same problem here, but with various HTTP methods.

When i try to send a PUT or POST request, some http status codes seems to be unrecognized and the app loops infinitely.

Status codes I tried:
- 201
- 202
- 401
- 402

Note that 400 and 404 errors are recognized and well handled.

**Comment by jarrodek** [comment]
The issue hast have been caused by the parser error. Since the issue was reported there were couple of updates related to this. Can you confirm that the issue is fixed already?

**Comment by jarrodek** [comment]
I'm closing this issue due to inactivity. Feel free to reopen it if needed.
