### ISSUE TITLE
Response headers may be absent

### ISSUE THREAD

**Issue by polkovnikov-ph** [jarrodek/ChromeRestClient#724]
```
extensions::uncaught_exception_handler:8 Error in event handler for sockets.tcp.onReceiveError: TypeError: this._connection.headers.has is not a function
    at SocketFetch.onResponseReady (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:32969:62)
    at SocketFetch.readSocketError (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:32719:12)
```

**Comment by jarrodek** [comment]
Thank you for issue report.
It has been fixed in https://github.com/jarrodek/socket-fetch/commit/1399908eff50058a6df7308f13ff9394e754790d
The update will be ready in coming days.
