### ISSUE TITLE
Fail to build the app due to without arc.json

### ISSUE THREAD

**Issue by markshao** [jarrodek/ChromeRestClient#789]
Try to build the app, but always fail due to could not find the "arc.json". I have try to scan the entire folder of the project , could not find the file .

```
 shaoyuliang@markshaos-MacBook-Pro  ~/xiaohongshu/code/github/ChromeRestClient   develop  gulp build --target beta --hotfix --build-only
[16:35:31] Using gulpfile ~/xiaohongshu/code/github/ChromeRestClient/gulpfile.js
[16:35:31] Starting 'build'...
[16:35:31] 'build' errored after 574 ms
[16:35:31] Error: Cannot find module '../../.credantials/arc.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shaoyuliang/xiaohongshu/code/github/ChromeRestClient/tasks/auth-client.js:8:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by jarrodek** [comment]
Hi,
I can't publish this file since it contains secrets for my account. However, I'll alter the build file to not require it at the build time.

**Comment by markshao** [comment]
That's will be cool, thanks.

**Comment by jarrodek** [comment]
It's already fixed. Pull develop branch to see changes.
