### ISSUE TITLE
ARC upgrade error

### ISSUE THREAD

**Issue by abxaz92** [jarrodek/ChromeRestClient#905]
The app errored during latest upgrade.

## Logs

```
Initializing upgrade
[1016] Checking if upgrade is required.
[1016] Deleting new databases if exists.
[1016] Initializing upgrade
[1016] Getting data from old database
Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Promise (chrome-extension://epgngalmiadbjnoompchcohonhidjanm/scripts/libs/app.importer.js:941:28)
    at arc.app.importer.getDatabase.then (chrome-extension://epgngalmiadbjnoompchcohonhidjanm/scripts/libs/app.importer.js:940:12)
[1016] Reading database takes longer than expected. You must have a lot of data in the datastore. Still working...
[1016] Reading database takes longer than expected. You must have a lot of data in the datastore. Still working...
```
## Versions
App: 8.15.57.289-beta
Chrome: 55.0.2883.52
Platform: Linux (-)

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.

It's happening on fresh install. It's trying to access data from the database that do not exists. I'll fix it right away.
