### ISSUE TITLE
Issue with ARC import. getting "unable to parse error"

### ISSUE THREAD

**Issue by ankur-bhardwaj** [jarrodek/ChromeRestClient#953]
arc-data-import::_importFileReady::JSON.parse::error Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at HTMLElement._computeFileImportPreview (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:91149:49)
    at HTMLElement._computeEffect (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4491:24)
    at HTMLElement._effectEffects (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4314:7)
    at HTMLElement._propertySetter (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4298:6)
    at HTMLElement.setter (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4377:6)
    at HTMLElement._importFileReady (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:91102:25)
    at HTMLElement.handler (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:3386:17)
    at HTMLElement.fire (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4152:6)
    at HTMLElement._readResult (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:25092:12)

**Comment by jarrodek** [comment]
Thank you for issue report.
Is that stable version of ARC? Have you tried beta version? Current beta contains redesigned import/export wit many bug fixes. It will be released soon as a stable version but it would be great if you could check the file with beta.
Instruction of how to get beta are here: https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel

**Comment by jarrodek** [comment]
This components was redesigned and new version should not have this bug.
